#
# Module manifest for module 'NetScalerToolkit.Statistics'
#
# Generated by: John Billekens
#
# Generated on: 3-6-2026
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'NetScalerToolkit.Statistics.psm1'

# Version number of this module.
ModuleVersion = '2026.914.1645'

# Supported PSEditions
# CompatiblePSEditions = @()

# ID used to uniquely identify this module
GUID = '44754188-7465-4302-9212-0a49d88e32dc'

# Author of this module
Author = 'John Billekens'

# Company or vendor of this module
CompanyName = 'John Billekens'

# Copyright statement for this module
Copyright = '(c) 2026 John Billekens. All rights reserved.'

# Description of the functionality provided by this module
Description = 'NetScaler NITRO API statistics functions.'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = 'Invoke-NSGetAAAStats', 'Invoke-NSGetACL6Stats', 
               'Invoke-NSGetACLStats', 'Invoke-NSGetAPISpecStats', 
               'Invoke-NSGetAppFlowStats', 'Invoke-NSGetAppFwPolicyLabelStats', 
               'Invoke-NSGetAppFwPolicyStats', 'Invoke-NSGetAppFwProfileStats', 
               'Invoke-NSGetAppFwStats', 'Invoke-NSGetAppQoEPolicyStats', 
               'Invoke-NSGetAppQoEStats', 'Invoke-NSGetAuditStats', 
               'Invoke-NSGetAuthenticationLoginSchemaPolicyStats', 
               'Invoke-NSGetAuthenticationOAuthIDPPolicyStats', 
               'Invoke-NSGetAuthenticationPolicyLabelStats', 
               'Invoke-NSGetAuthenticationPolicyStats', 
               'Invoke-NSGetAuthenticationSAMLIDPPolicyStats', 
               'Invoke-NSGetAuthenticationVServerStats', 
               'Invoke-NSGetAuthorizationPolicyLabelStats', 
               'Invoke-NSGetAutoscalePolicyStats', 
               'Invoke-NSGetBotPolicyLabelStats', 'Invoke-NSGetBotPolicyStats', 
               'Invoke-NSGetBotProfileStats', 'Invoke-NSGetBotStats', 
               'Invoke-NSGetBridgeStats', 'Invoke-NSGetCacheContentGroupStats', 
               'Invoke-NSGetCachePolicyLabelStats', 'Invoke-NSGetCachePolicyStats', 
               'Invoke-NSGetCacheStats', 'Invoke-NSGetCloudStats', 
               'Invoke-NSGetClusterInstanceStats', 'Invoke-NSGetClusterNodeStats', 
               'Invoke-NSGetCMPPolicyLabelStats', 'Invoke-NSGetCMPPolicyStats', 
               'Invoke-NSGetCMPStats', 
               'Invoke-NSGetContentInspectionPolicyLabelStats', 
               'Invoke-NSGetContentInspectionPolicyStats', 
               'Invoke-NSGetContentInSpecTionStats', 'Invoke-NSGetCRVServerStats', 
               'Invoke-NSGetCSVServerStats', 'Invoke-NSGetDenylistglobalStats', 
               'Invoke-NSGetDNSPolicyLabelStats', 'Invoke-NSGetDNSRecordSStats', 
               'Invoke-NSGetDNSStats', 'Invoke-NSGetFeoStats', 
               'Invoke-NSGetGSLBDomainStats', 
               'Invoke-NSGetGSLBServiceGroupMemberStats', 
               'Invoke-NSGetGSLBServiceGroupStats', 'Invoke-NSGetGSLBServiceStats', 
               'Invoke-NSGetGSLBSiteStats', 'Invoke-NSGetGSLBVServerStats', 
               'Invoke-NSGetHANodeStats', 'Invoke-NSGetICAPolicyStats', 
               'Invoke-NSGetIcaStats', 'Invoke-NSGetInatsessionStats', 
               'Invoke-NSGetINATStats', 'Invoke-NSGetInsightStats', 
               'Invoke-NSGetInterfaceStats', 'Invoke-NSGetIpsecalgcountersStats', 
               'Invoke-NSGetIpseccountersStats', 'Invoke-NSGetLBPolicyLabelStats', 
               'Invoke-NSGetLBPolicyStats', 'Invoke-NSGetLBVServerStats', 
               'Invoke-NSGetLimitIdentifierStats', 'Invoke-NSGetLldpStats', 
               'Invoke-NSGetLsndsliteStats', 'Invoke-NSGetLSNGroupStats', 
               'Invoke-NSGetLsnnat64Stats', 'Invoke-NSGetLSNPoolStats', 
               'Invoke-NSGetLsnStats', 'Invoke-NSGetMAPBMRStats', 
               'Invoke-NSGetMAPDomainStats', 'Invoke-NSGetNAT64Stats', 
               'Invoke-NSGetNsmemoryStats', 'Invoke-NSGetNsStats', 
               'Invoke-NSGetPartitionStats', 'Invoke-NSGetPBR6Stats', 
               'Invoke-NSGetPBRStats', 'Invoke-NSGetPCPServerStats', 
               'Invoke-NSGetProtocolHTTP2Stats', 'Invoke-NSGetProtocolHTTP3Stats', 
               'Invoke-NSGetProtocolHTTPStats', 'Invoke-NSGetProtocolICMPStats', 
               'Invoke-NSGetProtocolICMPV6Stats', 'Invoke-NSGetProtocolIpStats', 
               'Invoke-NSGetProtocolIPv6Stats', 'Invoke-NSGetProtocolMpTCPStats', 
               'Invoke-NSGetProtocolQUICBridgeStats', 
               'Invoke-NSGetProtocolQUICStats', 'Invoke-NSGetProtocolTCPStats', 
               'Invoke-NSGetProtocolUDPStats', 'Invoke-NSGetQosStats', 
               'Invoke-NSGetRDPStats', 'Invoke-NSGetResponderPolicyLabelStats', 
               'Invoke-NSGetResponderPolicyStats', 
               'Invoke-NSGetRewritePolicyLabelStats', 
               'Invoke-NSGetRewritePolicyStats', 'Invoke-NSGetRnat6Stats', 
               'Invoke-NSGetRnatipStats', 'Invoke-NSGetRnatStats', 
               'Invoke-NSGetServiceGroupMemberStats', 
               'Invoke-NSGetServiceGroupStats', 'Invoke-NSGetServiceStats', 
               'Invoke-NSGetSimpleACL6Stats', 'Invoke-NSGetSimpleACLStats', 
               'Invoke-NSGetSNMPStats', 'Invoke-NSGetSpilloverPolicyStats', 
               'Invoke-NSGetSSLStats', 'Invoke-NSGetSSLVServerStats', 
               'Invoke-NSGetStreamIdentifierStats', 'Invoke-NSGetSystemBwStats', 
               'Invoke-NSGetSystemCpuStats', 'Invoke-NSGetSystemMemoryStats', 
               'Invoke-NSGetSystemStats', 'Invoke-NSGetTMSessionPolicyStats', 
               'Invoke-NSGetTMTrafficPolicyStats', 
               'Invoke-NSGetTrafficDomainStats', 
               'Invoke-NSGetTransformPolicyLabelStats', 
               'Invoke-NSGetTransformPolicyStats', 'Invoke-NSGetTunnelip6Stats', 
               'Invoke-NSGetTunnelipStats', 'Invoke-NSGetTunnelTrafficPolicyStats', 
               'Invoke-NSGetUserVServerStats', 
               'Invoke-NSGetVideoOptimizationDetectionPolicyLabelStats', 
               'Invoke-NSGetVideoOptimizationDetectionPolicyStats', 
               'Invoke-NSGetVideoOptimizationPacingPolicyLabelStats', 
               'Invoke-NSGetVideoOptimizationPacingPolicyStats', 
               'Invoke-NSGetVideooptimizationStats', 'Invoke-NSGetVlanStats', 
               'Invoke-NSGetVPNStats', 'Invoke-NSGetVPNURLPolicyStats', 
               'Invoke-NSGetVPNVServerStats', 'Invoke-NSGetVxlanStats'

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
# VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        # Tags = @()

        # A URL to the license for this module.
        # LicenseUri = ''

        # A URL to the main website for this project.
        # ProjectUri = ''

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        # ReleaseNotes = ''

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

# SIG # Begin signature block
# MII6AgYJKoZIhvcNAQcCoII58zCCOe8CAQExDzANBglghkgBZQMEAgEFADB5Bgor
# BgEEAYI3AgEEoGswaTA0BgorBgEEAYI3AgEeMCYCAwEAAAQQH8w7YFlLCE63JNLG
# KX7zUQIBAAIBAAIBAAIBAAIBADAxMA0GCWCGSAFlAwQCAQUABCD1bAJBKI04ryls
# Rpg/c1VuM/vgIQNiWxCgRcNALqmhqqCCIiYwggXMMIIDtKADAgECAhBUmNLR1FsZ
# lUgTecgRwIeZMA0GCSqGSIb3DQEBDAUAMHcxCzAJBgNVBAYTAlVTMR4wHAYDVQQK
# ExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xSDBGBgNVBAMTP01pY3Jvc29mdCBJZGVu
# dGl0eSBWZXJpZmljYXRpb24gUm9vdCBDZXJ0aWZpY2F0ZSBBdXRob3JpdHkgMjAy
# MDAeFw0yMDA0MTYxODM2MTZaFw00NTA0MTYxODQ0NDBaMHcxCzAJBgNVBAYTAlVT
# MR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xSDBGBgNVBAMTP01pY3Jv
# c29mdCBJZGVudGl0eSBWZXJpZmljYXRpb24gUm9vdCBDZXJ0aWZpY2F0ZSBBdXRo
# b3JpdHkgMjAyMDCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBALORKgeD
# Bmf9np3gx8C3pOZCBH8Ppttf+9Va10Wg+3cL8IDzpm1aTXlT2KCGhFdFIMeiVPvH
# or+Kx24186IVxC9O40qFlkkN/76Z2BT2vCcH7kKbK/ULkgbk/WkTZaiRcvKYhOuD
# PQ7k13ESSCHLDe32R0m3m/nJxxe2hE//uKya13NnSYXjhr03QNAlhtTetcJtYmrV
# qXi8LW9J+eVsFBT9FMfTZRY33stuvF4pjf1imxUs1gXmuYkyM6Nix9fWUmcIxC70
# ViueC4fM7Ke0pqrrBc0ZV6U6CwQnHJFnni1iLS8evtrAIMsEGcoz+4m+mOJyoHI1
# vnnhnINv5G0Xb5DzPQCGdTiO0OBJmrvb0/gwytVXiGhNctO/bX9x2P29Da6SZEi3
# W295JrXNm5UhhNHvDzI9e1eM80UHTHzgXhgONXaLbZ7LNnSrBfjgc10yVpRnlyUK
# xjU9lJfnwUSLgP3B+PR0GeUw9gb7IVc+BhyLaxWGJ0l7gpPKWeh1R+g/OPTHU3mg
# trTiXFHvvV84wRPmeAyVWi7FQFkozA8kwOy6CXcjmTimthzax7ogttc32H83rwjj
# O3HbbnMbfZlysOSGM1l0tRYAe1BtxoYT2v3EOYI9JACaYNq6lMAFUSw0rFCZE4e7
# swWAsk0wAly4JoNdtGNz764jlU9gKL431VulAgMBAAGjVDBSMA4GA1UdDwEB/wQE
# AwIBhjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBTIftJqhSobyhmYBAcnz1AQ
# T2ioojAQBgkrBgEEAYI3FQEEAwIBADANBgkqhkiG9w0BAQwFAAOCAgEAr2rd5hnn
# LZRDGU7L6VCVZKUDkQKL4jaAOxWiUsIWGbZqWl10QzD0m/9gdAmxIR6QFm3FJI9c
# Zohj9E/MffISTEAQiwGf2qnIrvKVG8+dBetJPnSgaFvlVixlHIJ+U9pW2UYXeZJF
# xBA2CFIpF8svpvJ+1Gkkih6PsHMNzBxKq7Kq7aeRYwFkIqgyuH4yKLNncy2RtNwx
# AQv3Rwqm8ddK7VZgxCwIo3tAsLx0J1KH1r6I3TeKiW5niB31yV2g/rarOoDXGpc8
# FzYiQR6sTdWD5jw4vU8w6VSp07YEwzJ2YbuwGMUrGLPAgNW3lbBeUU0i/OxYqujY
# lLSlLu2S3ucYfCFX3VVj979tzR/SpncocMfiWzpbCNJbTsgAlrPhgzavhgplXHT2
# 6ux6anSg8Evu75SjrFDyh+3XOjCDyft9V77l4/hByuVkrrOj7FjshZrM77nq81YY
# uVxzmq/FdxeDWds3GhhyVKVB0rYjdaNDmuV3fJZ5t0GNv+zcgKCf0Xd1WF81E+Al
# GmcLfc4l+gcK5GEh2NQc5QfGNpn0ltDGFf5Ozdeui53bFv0ExpK91IjmqaOqu/dk
# ODtfzAzQNb50GQOmxapMomE2gj4d8yu8l13bS3g7LfU772Aj6PXsCyM2la+YZr9T
# 03u4aUoqlmZpxJTG9F9urJh4iIAGXKKy7aIwggbAMIIEqKADAgECAhMzAAYKGZiR
# OG4AHopYAAAABgoZMA0GCSqGSIb3DQEBDAUAMFoxCzAJBgNVBAYTAlVTMR4wHAYD
# VQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xKzApBgNVBAMTIk1pY3Jvc29mdCBJ
# RCBWZXJpZmllZCBDUyBFT0MgQ0EgMDMwHhcNMjYwOTEyMjEzODAwWhcNMjYwOTE1
# MjEzODAwWjCBgzELMAkGA1UEBhMCTkwxFjAUBgNVBAgTDU5vb3JkLUJyYWJhbnQx
# EjAQBgNVBAcTCVNjaGlqbmRlbDEjMCEGA1UEChMaSm9obiBCaWxsZWtlbnMgQ29u
# c3VsdGFuY3kxIzAhBgNVBAMTGkpvaG4gQmlsbGVrZW5zIENvbnN1bHRhbmN5MIIB
# ojANBgkqhkiG9w0BAQEFAAOCAY8AMIIBigKCAYEAiwPPCsKKgQzjkUVmMnYZL6BZ
# n1ho+v1PrJ+aF+m76ikQCs4iFRyz0J23vcQyGDiKXDwXb4iVlcHlomA9fdxYJDZP
# x5K7wc4ObclPy5qGEP3EqrzhO8YaZKMSvSxgTbI1Sbmyh2w0mfWT+Sj27SPNXbdA
# ndB83BRpiDhv2R00J8QotfeNCYwbraqLHAjLQKe4EH6iB6KnewONArE35pTXjmMi
# uD7O+muKigdfI75Vi2ApteGTntYHkjmcpdL1pkwGUgDzRTlIhYYvdwef9dANvUv0
# noMESzawFx1iGdXJPvOUieUeVMSerqUcRmn3fc5IDH5j9eJpiuC5kttgITeMe3dR
# 5rbLb238hn3bjWwrAgNWnKmcsj4KvA0mj8PDqpe1r5mUpkwnK/X7J8CDwGFuZx9d
# EwmFNh47t3xBqGyc49+Eo1FyoyAxGQBVK1IEt/I0Z0Jr/vvmoUsenG4Yi6I4xJ80
# LjYHtdbhkjQEc0Vl0NIW6fNwNzkL7la50ArZ21RJAgMBAAGjggHTMIIBzzAMBgNV
# HRMBAf8EAjAAMA4GA1UdDwEB/wQEAwIHgDA6BgNVHSUEMzAxBgorBgEEAYI3YQEA
# BggrBgEFBQcDAwYZKwYBBAGCN2HK9PELgrHSgxH33KNOluu6MTAdBgNVHQ4EFgQU
# VKEfunxRautOaV5ZiyJcYV3/D0swHwYDVR0jBBgwFoAUa16lNMMFxWJKIVqOq3Ng
# YtSsY4UwZwYDVR0fBGAwXjBcoFqgWIZWaHR0cDovL3d3dy5taWNyb3NvZnQuY29t
# L3BraW9wcy9jcmwvTWljcm9zb2Z0JTIwSUQlMjBWZXJpZmllZCUyMENTJTIwRU9D
# JTIwQ0ElMjAwMy5jcmwwdAYIKwYBBQUHAQEEaDBmMGQGCCsGAQUFBzAChlhodHRw
# Oi8vd3d3Lm1pY3Jvc29mdC5jb20vcGtpb3BzL2NlcnRzL01pY3Jvc29mdCUyMElE
# JTIwVmVyaWZpZWQlMjBDUyUyMEVPQyUyMENBJTIwMDMuY3J0MFQGA1UdIARNMEsw
# SQYEVR0gADBBMD8GCCsGAQUFBwIBFjNodHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20v
# cGtpb3BzL0RvY3MvUmVwb3NpdG9yeS5odG0wDQYJKoZIhvcNAQEMBQADggIBAIgx
# tmDIR7f1Oad8sCEWYsCusiu5wRjLntVkxzuEeofgfiP17aiO59HDHesSpTUMafnb
# BFDKwCIIcnbum+RsTmxzfBXnidQTydycqnG76towe44UWDdPtEqZ2ec1d9WM4TXN
# +CPK1aLpYwYogUGiWzinY5RKaHs3EK/t7Cf7mJx312ItGHKSWTdu1UkyDqLxxM/v
# 0cT2PBWrwPVrFoRDIEp5oj8xg01aG4M/sZKX8lBuzdSuDEmYdhS30/UKQ3dgQjpT
# ggMV+acJg+lPyfwUCrgd0qga295zco1P5VpqGHfswXNXIizPajtLthFWqvoeLpR1
# 7wNL5GtNPCIOKERW7xYyzJZhPl7Xm1ccsDHOpNqQYUq1G8MlXA7+BYs8Ga2xub6A
# nezhqfMB53LOSqdOmJxJvkG7t5BqhAEvqvupHC6lWNnWPdJUq2XEtZ2rsMir9wU0
# ly0GJBLO17OIjKk5av2087EsyQO3+bxAVWLUUGVwqR3mkWPlSM+whpoYvqRkxKiv
# 42Wu2Mt9vaWpv1YlhuyENaaRs6h+V5EhKEi+LvAkjeHv8Sv6DFjwQPX7DQJf08t4
# r78UxDeylfYNpbGwLmysPh7z92qsRe5GNcJwt+061cijnuvfY0uL5UYS/gRMkBVP
# +Zi5WlkAi0ZKpF6wiUuuQ162OHuZTLPQ74PtxRGvMIIGwDCCBKigAwIBAgITMwAG
# ChmYkThuAB6KWAAAAAYKGTANBgkqhkiG9w0BAQwFADBaMQswCQYDVQQGEwJVUzEe
# MBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSswKQYDVQQDEyJNaWNyb3Nv
# ZnQgSUQgVmVyaWZpZWQgQ1MgRU9DIENBIDAzMB4XDTI2MDkxMjIxMzgwMFoXDTI2
# MDkxNTIxMzgwMFowgYMxCzAJBgNVBAYTAk5MMRYwFAYDVQQIEw1Ob29yZC1CcmFi
# YW50MRIwEAYDVQQHEwlTY2hpam5kZWwxIzAhBgNVBAoTGkpvaG4gQmlsbGVrZW5z
# IENvbnN1bHRhbmN5MSMwIQYDVQQDExpKb2huIEJpbGxla2VucyBDb25zdWx0YW5j
# eTCCAaIwDQYJKoZIhvcNAQEBBQADggGPADCCAYoCggGBAIsDzwrCioEM45FFZjJ2
# GS+gWZ9YaPr9T6yfmhfpu+opEArOIhUcs9Cdt73EMhg4ilw8F2+IlZXB5aJgPX3c
# WCQ2T8eSu8HODm3JT8uahhD9xKq84TvGGmSjEr0sYE2yNUm5sodsNJn1k/ko9u0j
# zV23QJ3QfNwUaYg4b9kdNCfEKLX3jQmMG62qixwIy0CnuBB+ogeip3sDjQKxN+aU
# 145jIrg+zvpriooHXyO+VYtgKbXhk57WB5I5nKXS9aZMBlIA80U5SIWGL3cHn/XQ
# Db1L9J6DBEs2sBcdYhnVyT7zlInlHlTEnq6lHEZp933OSAx+Y/XiaYrguZLbYCE3
# jHt3Uea2y29t/IZ9241sKwIDVpypnLI+CrwNJo/Dw6qXta+ZlKZMJyv1+yfAg8Bh
# bmcfXRMJhTYeO7d8QahsnOPfhKNRcqMgMRkAVStSBLfyNGdCa/775qFLHpxuGIui
# OMSfNC42B7XW4ZI0BHNFZdDSFunzcDc5C+5WudAK2dtUSQIDAQABo4IB0zCCAc8w
# DAYDVR0TAQH/BAIwADAOBgNVHQ8BAf8EBAMCB4AwOgYDVR0lBDMwMQYKKwYBBAGC
# N2EBAAYIKwYBBQUHAwMGGSsGAQQBgjdhyvTxC4Kx0oMR99yjTpbrujEwHQYDVR0O
# BBYEFFShH7p8UWrrTmleWYsiXGFd/w9LMB8GA1UdIwQYMBaAFGtepTTDBcViSiFa
# jqtzYGLUrGOFMGcGA1UdHwRgMF4wXKBaoFiGVmh0dHA6Ly93d3cubWljcm9zb2Z0
# LmNvbS9wa2lvcHMvY3JsL01pY3Jvc29mdCUyMElEJTIwVmVyaWZpZWQlMjBDUyUy
# MEVPQyUyMENBJTIwMDMuY3JsMHQGCCsGAQUFBwEBBGgwZjBkBggrBgEFBQcwAoZY
# aHR0cDovL3d3dy5taWNyb3NvZnQuY29tL3BraW9wcy9jZXJ0cy9NaWNyb3NvZnQl
# MjBJRCUyMFZlcmlmaWVkJTIwQ1MlMjBFT0MlMjBDQSUyMDAzLmNydDBUBgNVHSAE
# TTBLMEkGBFUdIAAwQTA/BggrBgEFBQcCARYzaHR0cDovL3d3dy5taWNyb3NvZnQu
# Y29tL3BraW9wcy9Eb2NzL1JlcG9zaXRvcnkuaHRtMA0GCSqGSIb3DQEBDAUAA4IC
# AQCIMbZgyEe39TmnfLAhFmLArrIrucEYy57VZMc7hHqH4H4j9e2ojufRwx3rEqU1
# DGn52wRQysAiCHJ27pvkbE5sc3wV54nUE8ncnKpxu+raMHuOFFg3T7RKmdnnNXfV
# jOE1zfgjytWi6WMGKIFBols4p2OUSmh7NxCv7ewn+5icd9diLRhyklk3btVJMg6i
# 8cTP79HE9jwVq8D1axaEQyBKeaI/MYNNWhuDP7GSl/JQbs3UrgxJmHYUt9P1CkN3
# YEI6U4IDFfmnCYPpT8n8FAq4HdKoGtvec3KNT+Vaahh37MFzVyIsz2o7S7YRVqr6
# Hi6Ude8DS+RrTTwiDihEVu8WMsyWYT5e15tXHLAxzqTakGFKtRvDJVwO/gWLPBmt
# sbm+gJ3s4anzAedyzkqnTpicSb5Bu7eQaoQBL6r7qRwupVjZ1j3SVKtlxLWdq7DI
# q/cFNJctBiQSzteziIypOWr9tPOxLMkDt/m8QFVi1FBlcKkd5pFj5UjPsIaaGL6k
# ZMSor+NlrtjLfb2lqb9WJYbshDWmkbOofleRIShIvi7wJI3h7/Er+gxY8ED1+w0C
# X9PLeK+/FMQ3spX2DaWxsC5srD4e8/dqrEXuRjXCcLftOtXIo57r32NLi+VGEv4E
# TJAVT/mYuVpZAItGSqResIlLrkNetjh7mUyz0O+D7cURrzCCBygwggUQoAMCAQIC
# EzMAAAAVBT5uGY6TKdkAAAAAABUwDQYJKoZIhvcNAQEMBQAwYzELMAkGA1UEBhMC
# VVMxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjE0MDIGA1UEAxMrTWlj
# cm9zb2Z0IElEIFZlcmlmaWVkIENvZGUgU2lnbmluZyBQQ0EgMjAyMTAeFw0yNjAz
# MjYxODExMjhaFw0zMTAzMjYxODExMjhaMFoxCzAJBgNVBAYTAlVTMR4wHAYDVQQK
# ExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xKzApBgNVBAMTIk1pY3Jvc29mdCBJRCBW
# ZXJpZmllZCBDUyBFT0MgQ0EgMDMwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIK
# AoICAQDg9Ms9AqovDnMePvMOe+KybhCd8+lokzYORlS3kBVXseecbyGwBcsenlm5
# bLtMGPjiIFLzBQF+ghlVV/U29q5GcdeEEBCHTTGhL2koIrLc4UrliMRcbv9mOMtR
# /l7/xAmv0Fx4BJHn1dHt37fvrBqXmKjKfGf5DpyO/+hnV7TEreMtS19iO+bjZ/9H
# npg3PCk0e7YSbRTFkx97FZwRWpC4s3NepRfRXQh/WMAj7JmsYeVZohi4TF5yW2JM
# rJZqwHcyzJZYtD2Hlno5ZEJkdiZcEaxHOobmwO06Z1J9c23ps9PGIhGaq1sKLEAz
# 9Doc5rLkYWGteDrscKhAp2kIc/oYlH9Ij6BkOqqgWINEkEtC8ZNG1Mak+h3o65aj
# 0iQKmdxW7IZaHO5cuyoMi+KtYfXeIIg3sVIbS2EL8kUtsDGdEqNqAq/isqTi1jXq
# Le6iKp1ni1SPdvPW9G03CTsYF68b/yuIQRwbdoBCXemMNJCS0dorCRY4b2WAAy4n
# g7SANcEgrBgZf535+QfLU5hGzrKjIpbMabauWb5FKWUKkMsPcXFkXRWO4noKPm4K
# WlFypqOpbJ/KONVReIlxHQRegAOBzIhRB7gr9IDQ1sc2MgOgQ+xVGW4oq4HD0mfA
# iwiyLskZrkaQ7JoanYjBNcR9RS26YxAVbcBtLitFTzCIEg5ZdQIDAQABo4IB3DCC
# AdgwDgYDVR0PAQH/BAQDAgGGMBAGCSsGAQQBgjcVAQQDAgEAMB0GA1UdDgQWBBRr
# XqU0wwXFYkohWo6rc2Bi1KxjhTBUBgNVHSAETTBLMEkGBFUdIAAwQTA/BggrBgEF
# BQcCARYzaHR0cDovL3d3dy5taWNyb3NvZnQuY29tL3BraW9wcy9Eb2NzL1JlcG9z
# aXRvcnkuaHRtMBkGCSsGAQQBgjcUAgQMHgoAUwB1AGIAQwBBMBIGA1UdEwEB/wQI
# MAYBAf8CAQAwHwYDVR0jBBgwFoAU2UEpsA8PY2zvadf1zSmepEhqMOYwcAYDVR0f
# BGkwZzBloGOgYYZfaHR0cDovL3d3dy5taWNyb3NvZnQuY29tL3BraW9wcy9jcmwv
# TWljcm9zb2Z0JTIwSUQlMjBWZXJpZmllZCUyMENvZGUlMjBTaWduaW5nJTIwUENB
# JTIwMjAyMS5jcmwwfQYIKwYBBQUHAQEEcTBvMG0GCCsGAQUFBzAChmFodHRwOi8v
# d3d3Lm1pY3Jvc29mdC5jb20vcGtpb3BzL2NlcnRzL01pY3Jvc29mdCUyMElEJTIw
# VmVyaWZpZWQlMjBDb2RlJTIwU2lnbmluZyUyMFBDQSUyMDIwMjEuY3J0MA0GCSqG
# SIb3DQEBDAUAA4ICAQBdbiI8zwXLX8glJEh/8Q22UMCUhWBO46Z9FPhwOR3mdlqR
# VLkYOon/MczUwrjDhx3X99SPH5PSflkGoTvnO9ZWHM5YFVYpO7NYuB+mfVSGAGZw
# iGOASWk0i2B7vn9nElJJmoiXxugfH5YdBsrUgTt0AFNXkzmqTgk+S1Hxb1u/0HCq
# EHVZPk2A/6eJXYbtpRM5Fcz00jisUl9BRZgSebODV85bBzOveqyC3f0PnHCxRJNh
# Mb8xP/sB/VI7pf2rheSV7zqUSv8vn/fIMblXeaVIlpqoq8SP9BJMjE/CoVXJxnkZ
# QRM1Fa7kN9yztvReOhxSgPgpZx/Xl/jkwyEFVJTBfBp3sTgfIc/pmqv2ehtakL2A
# Ej78EmOPQohxJT3wyX+P78GA25tLpAvzj3RMMHd8z18ZuuVi+60MAzGpOASH1L8N
# lr3fZRZnQO+pyye2DCvYmHaIfdUgYJqn7noxxGVv89+RaETh1tgCDvwNpFCSG7vl
# 5A4ako+2fx409r9TWjXC7Oif1IQ5ZJzB4Rf8GvBiHYjvMmHpledp1FGRLdSRFVpC
# 3/OKpZY6avIqZp7+8pP/WQP903DdgrvAT6W4xPOBxXPa4tGksN3SuqJaiFYHSNye
# Bufn8iseujW4IbBSbHD4BPqbF3qZ+7nG9d/d/G2/Lx4kH9cCmBfmsZdSkHmukDCC
# B54wggWGoAMCAQICEzMAAAAHh6M0o3uljhwAAAAAAAcwDQYJKoZIhvcNAQEMBQAw
# dzELMAkGA1UEBhMCVVMxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjFI
# MEYGA1UEAxM/TWljcm9zb2Z0IElkZW50aXR5IFZlcmlmaWNhdGlvbiBSb290IENl
# cnRpZmljYXRlIEF1dGhvcml0eSAyMDIwMB4XDTIxMDQwMTIwMDUyMFoXDTM2MDQw
# MTIwMTUyMFowYzELMAkGA1UEBhMCVVMxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jw
# b3JhdGlvbjE0MDIGA1UEAxMrTWljcm9zb2Z0IElEIFZlcmlmaWVkIENvZGUgU2ln
# bmluZyBQQ0EgMjAyMTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBALLw
# wK8ZiCji3VR6TElsaQhVCbRS/3pK+MHrJSj3Zxd3KU3rlfL3qrZilYKJNqztA9OQ
# acr1AwoNcHbKBLbsQAhBnIB34zxf52bDpIO3NJlfIaTE/xrweLoQ71lzCHkD7A4A
# s1Bs076Iu+mA6cQzsYYH/Cbl1icwQ6C65rU4V9NQhNUwgrx9rGQ//h890Q8JdjLL
# w0nV+ayQ2Fbkd242o9kH82RZsH3HEyqjAB5a8+Ae2nPIPc8sZU6ZE7iRrRZywRmr
# KDp5+TcmJX9MRff241UaOBs4NmHOyke8oU1TYrkxh+YeHgfWo5tTgkoSMoayqoDp
# HOLJs+qG8Tvh8SnifW2Jj3+ii11TS8/FGngEaNAWrbyfNrC69oKpRQXY9bGH6jn9
# NEJv9weFxhTwyvx9OJLXmRGbAUXN1U9nf4lXezky6Uh/cgjkVd6CGUAf0K+Jw+GE
# /5VpIVbcNr9rNE50Sbmy/4RTCEGvOq3GhjITbCa4crCzTTHgYYjHs1NbOc6brH+e
# KpWLtr+bGecy9CrwQyx7S/BfYJ+ozst7+yZtG2wR461uckFu0t+gCwLdN0A6cFtS
# RtR8bvxVFyWwTtgMMFRuBa3vmUOTnfKLsLefRaQcVTgRnzeLzdpt32cdYKp+dhr2
# ogc+qM6K4CBI5/j4VFyC4QFeUP2YAidLtvpXRRo3AgMBAAGjggI1MIICMTAOBgNV
# HQ8BAf8EBAMCAYYwEAYJKwYBBAGCNxUBBAMCAQAwHQYDVR0OBBYEFNlBKbAPD2Ns
# 72nX9c0pnqRIajDmMFQGA1UdIARNMEswSQYEVR0gADBBMD8GCCsGAQUFBwIBFjNo
# dHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20vcGtpb3BzL0RvY3MvUmVwb3NpdG9yeS5o
# dG0wGQYJKwYBBAGCNxQCBAweCgBTAHUAYgBDAEEwDwYDVR0TAQH/BAUwAwEB/zAf
# BgNVHSMEGDAWgBTIftJqhSobyhmYBAcnz1AQT2ioojCBhAYDVR0fBH0wezB5oHeg
# dYZzaHR0cDovL3d3dy5taWNyb3NvZnQuY29tL3BraW9wcy9jcmwvTWljcm9zb2Z0
# JTIwSWRlbnRpdHklMjBWZXJpZmljYXRpb24lMjBSb290JTIwQ2VydGlmaWNhdGUl
# MjBBdXRob3JpdHklMjAyMDIwLmNybDCBwwYIKwYBBQUHAQEEgbYwgbMwgYEGCCsG
# AQUFBzAChnVodHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20vcGtpb3BzL2NlcnRzL01p
# Y3Jvc29mdCUyMElkZW50aXR5JTIwVmVyaWZpY2F0aW9uJTIwUm9vdCUyMENlcnRp
# ZmljYXRlJTIwQXV0aG9yaXR5JTIwMjAyMC5jcnQwLQYIKwYBBQUHMAGGIWh0dHA6
# Ly9vbmVvY3NwLm1pY3Jvc29mdC5jb20vb2NzcDANBgkqhkiG9w0BAQwFAAOCAgEA
# fyUqnv7Uq+rdZgrbVyNMul5skONbhls5fccPlmIbzi+OwVdPQ4H55v7VOInnmezQ
# EeW4LqK0wja+fBznANbXLB0KrdMCbHQpbLvG6UA/Xv2pfpVIE1CRFfNF4XKO8XYE
# a3oW8oVH+KZHgIQRIwAbyFKQ9iyj4aOWeAzwk+f9E5StNp5T8FG7/VEURIVWArbA
# zPt9ThVN3w1fAZkF7+YU9kbq1bCR2YD+MtunSQ1Rft6XG7b4e0ejRA7mB2IoX5hN
# h3UEauY0byxNRG+fT2MCEhQl9g2i2fs6VOG19CNep7SquKaBjhWmirYyANb0RJSL
# WjinMLXNOAga10n8i9jqeprzSMU5ODmrMCJE12xS/NWShg/tuLjAsKP6SzYZ+1Ry
# 358ZTFcx0FS/mx2vSoU8s8HRvy+rnXqyUJ9HBqS0DErVLjQwK8VtsBdekBmdTbQV
# oCgPCqr+PDPB3xajYnzevs7eidBsM71PINK2BoE2UfMwxCCX3mccFgx6UsQeRSdV
# VVNSyALQe6PT12418xon2iDGE81OGCreLzDcMAZnrUAx4XQLUz6ZTl65yPUiOh3k
# 7Yww94lDf+8oG2oZmDh5O1Qe38E+M3vhKwmzIeoB1dVLlz4i3IpaDcR+iuGjH2Td
# aC1ZOmBXiCRKJLj4DT2uhJ04ji+tHD6n58vhavFIrmcxghcyMIIXLgIBATBxMFox
# CzAJBgNVBAYTAlVTMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xKzAp
# BgNVBAMTIk1pY3Jvc29mdCBJRCBWZXJpZmllZCBDUyBFT0MgQ0EgMDMCEzMABgoZ
# mJE4bgAeilgAAAAGChkwDQYJYIZIAWUDBAIBBQCgXjAQBgorBgEEAYI3AgEMMQIw
# ADAZBgkqhkiG9w0BCQMxDAYKKwYBBAGCNwIBBDAvBgkqhkiG9w0BCQQxIgQggulO
# gvAvXDJ0BZYDuMW1qSPTQDInM4Wz2KSbnDlJDRcwDQYJKoZIhvcNAQEBBQAEggGA
# QvdpBsaBFskPal2eS8mHPPduaLyyh7qtVyqBNpt5uXFwt3hpJz1+AAflasKj/KqC
# NGenZZeCEeNZATQXabCgop3ZEXjhTtzduLgO3GLXs23NahzHl6LM1v/rgAZS65VH
# R1EZ3esi4lDoa7Bib6BAZmrQ5XGs5Wm/a6FQfOjOkMh5i40egCOMe/Q8Y2xhu6gi
# RDRCthlm1NKDWPBlEW67hEr54AEkdD9cj5j1uE0aN2dMYVi4s/syCvl5tUXZWByo
# 8D9pc/xp5UPHX7EmiuunLMSgZhlKeyFcLF2WORe+f9/n5i69SP/EyBzOQFaewFsL
# xcWuLAX34EHwsLdwrW/V4hgT0kbdeB+gP/ErZWBTPM872FHSVhF9I+smbq004hNH
# mbZAW4TudaNYuSuRoX1/zyCMvrhqFYuf0EYcwoCpw34RQ4DTa+dZHC+7T4iMFuoo
# JEnJU0keBBjfbIQtFJHIjdg3kG8A+58zczTJ20bI5aUdG3+mpFalR1ExDLFZTYHS
# oYIUsjCCFK4GCisGAQQBgjcDAwExghSeMIIUmgYJKoZIhvcNAQcCoIIUizCCFIcC
# AQMxDzANBglghkgBZQMEAgEFADCCAWoGCyqGSIb3DQEJEAEEoIIBWQSCAVUwggFR
# AgEBBgorBgEEAYRZCgMBMDEwDQYJYIZIAWUDBAIBBQAEIFj72JAhVvP1rPHk6lPR
# MpPPNVTKokzTeGHAKH/wWhMlAgZqNTDLvksYEzIwMjYwOTE0MTQzOTMwLjU0OVow
# BIACAfSggemkgeYwgeMxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9u
# MRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRp
# b24xLTArBgNVBAsTJE1pY3Jvc29mdCBJcmVsYW5kIE9wZXJhdGlvbnMgTGltaXRl
# ZDEnMCUGA1UECxMeblNoaWVsZCBUU1MgRVNOOjQ5MUEtMDVFMC1EOTQ3MTUwMwYD
# VQQDEyxNaWNyb3NvZnQgUHVibGljIFJTQSBUaW1lIFN0YW1waW5nIEF1dGhvcml0
# eaCCDykwggeCMIIFaqADAgECAhMzAAAABeXPD/9mLsmHAAAAAAAFMA0GCSqGSIb3
# DQEBDAUAMHcxCzAJBgNVBAYTAlVTMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9y
# YXRpb24xSDBGBgNVBAMTP01pY3Jvc29mdCBJZGVudGl0eSBWZXJpZmljYXRpb24g
# Um9vdCBDZXJ0aWZpY2F0ZSBBdXRob3JpdHkgMjAyMDAeFw0yMDExMTkyMDMyMzFa
# Fw0zNTExMTkyMDQyMzFaMGExCzAJBgNVBAYTAlVTMR4wHAYDVQQKExVNaWNyb3Nv
# ZnQgQ29ycG9yYXRpb24xMjAwBgNVBAMTKU1pY3Jvc29mdCBQdWJsaWMgUlNBIFRp
# bWVzdGFtcGluZyBDQSAyMDIwMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKC
# AgEAnnznUmP94MWfBX1jtQYioxwe1+eXM9ETBb1lRkd3kcFdcG9/sqtDlwxKoVIc
# aqDb+omFio5DHC4RBcbyQHjXCwMk/l3TOYtgoBjxnG/eViS4sOx8y4gSq8Zg49RE
# Af5huXhIkQRKe3Qxs8Sgp02KHAznEa/Ssah8nWo5hJM1xznkRsFPu6rfDHeZeG1W
# a1wISvlkpOQooTULFm809Z0ZYlQ8Lp7i5F9YciFlyAKwn6yjN/kR4fkquUWfGmMo
# pNq/B8U/pdoZkZZQbxNlqJOiBGgCWpx69uKqKhTPVi3gVErnc/qi+dR8A2MiAz0k
# N0nh7SqINGbmw5OIRC0EsZ31WF3Uxp3GgZwetEKxLms73KG/Z+MkeuaVDQQheang
# OEMGJ4pQZH55ngI0Tdy1bi69INBV5Kn2HVJo9XxRYR/JPGAaM6xGl57Ei95HUw9N
# V/uC3yFjrhc087qLJQawSC3xzY/EXzsT4I7sDbxOmM2rl4uKK6eEpurRduOQ2hTk
# mG1hSuWYBunFGNv21Kt4N20AKmbeuSnGnsBCd2cjRKG79+TX+sTehawOoxfeOO/j
# R7wo3liwkGdzPJYHgnJ54UxbckF914AqHOiEV7xTnD1a69w/UTxwjEugpIPMIIE6
# 7SFZ2PMo27xjlLAHWW3l1CEAFjLNHd3EQ79PUr8FUXetXr0CAwEAAaOCAhswggIX
# MA4GA1UdDwEB/wQEAwIBhjAQBgkrBgEEAYI3FQEEAwIBADAdBgNVHQ4EFgQUa2ko
# OjUvSGNAz3vYr0npPtk92yEwVAYDVR0gBE0wSzBJBgRVHSAAMEEwPwYIKwYBBQUH
# AgEWM2h0dHA6Ly93d3cubWljcm9zb2Z0LmNvbS9wa2lvcHMvRG9jcy9SZXBvc2l0
# b3J5Lmh0bTATBgNVHSUEDDAKBggrBgEFBQcDCDAZBgkrBgEEAYI3FAIEDB4KAFMA
# dQBiAEMAQTAPBgNVHRMBAf8EBTADAQH/MB8GA1UdIwQYMBaAFMh+0mqFKhvKGZgE
# ByfPUBBPaKiiMIGEBgNVHR8EfTB7MHmgd6B1hnNodHRwOi8vd3d3Lm1pY3Jvc29m
# dC5jb20vcGtpb3BzL2NybC9NaWNyb3NvZnQlMjBJZGVudGl0eSUyMFZlcmlmaWNh
# dGlvbiUyMFJvb3QlMjBDZXJ0aWZpY2F0ZSUyMEF1dGhvcml0eSUyMDIwMjAuY3Js
# MIGUBggrBgEFBQcBAQSBhzCBhDCBgQYIKwYBBQUHMAKGdWh0dHA6Ly93d3cubWlj
# cm9zb2Z0LmNvbS9wa2lvcHMvY2VydHMvTWljcm9zb2Z0JTIwSWRlbnRpdHklMjBW
# ZXJpZmljYXRpb24lMjBSb290JTIwQ2VydGlmaWNhdGUlMjBBdXRob3JpdHklMjAy
# MDIwLmNydDANBgkqhkiG9w0BAQwFAAOCAgEAX4h2x35ttVoVdedMeGj6TuHYRJkl
# FaW4sTQ5r+k77iB79cSLNe+GzRjv4pVjJviceW6AF6ycWoEYR0LYhaa0ozJLU5Yi
# +LCmcrdovkl53DNt4EXs87KDogYb9eGEndSpZ5ZM74LNvVzY0/nPISHz0Xva71Qj
# D4h+8z2XMOZzY7YQ0Psw+etyNZ1CesufU211rLslLKsO8F2aBs2cIo1k+aHOhrw9
# xw6JCWONNboZ497mwYW5EfN0W3zL5s3ad4Xtm7yFM7Ujrhc0aqy3xL7D5FR2J7x9
# cLWMq7eb0oYioXhqV2tgFqbKHeDick+P8tHYIFovIP7YG4ZkJWag1H91KlELGWi3
# SLv10o4KGag42pswjybTi4toQcC/irAodDW8HNtX+cbz0sMptFJK+KObAnDFHEsu
# kxD+7jFfEV9Hh/+CSxKRsmnuiovCWIOb+H7DRon9TlxydiFhvu88o0w35JkNbJxT
# k4MhF/KgaXn0GxdH8elEa2Imq45gaa8D+mTm8LWVydt4ytxYP/bqjN49D9NZ81co
# E6aQWm88TwIf4R4YZbOpMKN0CyejaPNN41LGXHeCUMYmBx3PkP8ADHD1J2Cr/6tj
# uOOCztfp+o9Nc+ZoIAkpUcA/X2gSMkgHAPUvIdtoSAHEUKiBhI6JQivRepyvWcl+
# JYbYbBh7pmgAXVswggefMIIFh6ADAgECAhMzAAAAWvYNZ4yF7d0IAAAAAABaMA0G
# CSqGSIb3DQEBDAUAMGExCzAJBgNVBAYTAlVTMR4wHAYDVQQKExVNaWNyb3NvZnQg
# Q29ycG9yYXRpb24xMjAwBgNVBAMTKU1pY3Jvc29mdCBQdWJsaWMgUlNBIFRpbWVz
# dGFtcGluZyBDQSAyMDIwMB4XDTI2MDEwODE4NTkwM1oXDTI3MDEwNzE4NTkwM1ow
# geMxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdS
# ZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xLTArBgNVBAsT
# JE1pY3Jvc29mdCBJcmVsYW5kIE9wZXJhdGlvbnMgTGltaXRlZDEnMCUGA1UECxMe
# blNoaWVsZCBUU1MgRVNOOjQ5MUEtMDVFMC1EOTQ3MTUwMwYDVQQDEyxNaWNyb3Nv
# ZnQgUHVibGljIFJTQSBUaW1lIFN0YW1waW5nIEF1dGhvcml0eTCCAiIwDQYJKoZI
# hvcNAQEBBQADggIPADCCAgoCggIBAO/0O0eWjgUb9rnHcQLRdfWPN4H+91a3Ynla
# P46E1m4uD+JKx6csWMStX79fxLJUAqHJqQWE19UlNMhS9jEB32dAJ4yuWsHyUuM+
# dphjDz4E5jl4gYGZEmaOrKvNt+KqlFayyg/oTg3BlLRu4aBq8668A5qlHcfsuh6D
# dSqFID1ixJFZzHrZFG1iGBG7U1Bn2ONLDo7jbwX5rMcPduTAUw/c7M3WhSxQBuZp
# Qiz8RQGKIqCKfIxgQkKdzpCpU0SWQOE/DgTXbz3c15KMRCdkGlL2zb+lnuSV4sse
# Qm3qflZiZckLyn2xJI8ZXDkq+Ig+b/rsPPIfI8di228WvK1j67JXpyeVCaSUO9Er
# zlLnTrnjQkeXVQIp73xuVBVrmvoTf/v4a7MnrmuKSyIXc5vJUHEGB345+O8omFt1
# w8b+Xg9D9PKIRqDPEv7HRk0C+Yvxu8FvHJvSocSIZK+v/FmKFOipYnpP76yAmJNn
# yheucShOgk8QiU53USn/+AyMb7xW905gZnyNqb29HeVdQ175pDHJGEz8Cx5wiHeV
# liGz5hABucFDylR9z3LSTmB6+3ZuIxeG9BZS46P6ANPkuVuD5m8wgc7GLLzg73Cs
# DF09ukt8Uf8dTcMBX3ro+7/k9M6Xt8WPG7IL9v/4DvyMY03tkb9Y9Ri6HWavXRPY
# RCUePspPAgMBAAGjggHLMIIBxzAdBgNVHQ4EFgQUjmOyQ6twMcP1ZbRytJxI4fnX
# mcIwHwYDVR0jBBgwFoAUa2koOjUvSGNAz3vYr0npPtk92yEwbAYDVR0fBGUwYzBh
# oF+gXYZbaHR0cDovL3d3dy5taWNyb3NvZnQuY29tL3BraW9wcy9jcmwvTWljcm9z
# b2Z0JTIwUHVibGljJTIwUlNBJTIwVGltZXN0YW1waW5nJTIwQ0ElMjAyMDIwLmNy
# bDB5BggrBgEFBQcBAQRtMGswaQYIKwYBBQUHMAKGXWh0dHA6Ly93d3cubWljcm9z
# b2Z0LmNvbS9wa2lvcHMvY2VydHMvTWljcm9zb2Z0JTIwUHVibGljJTIwUlNBJTIw
# VGltZXN0YW1waW5nJTIwQ0ElMjAyMDIwLmNydDAMBgNVHRMBAf8EAjAAMBYGA1Ud
# JQEB/wQMMAoGCCsGAQUFBwMIMA4GA1UdDwEB/wQEAwIHgDBmBgNVHSAEXzBdMFEG
# DCsGAQQBgjdMg30BATBBMD8GCCsGAQUFBwIBFjNodHRwOi8vd3d3Lm1pY3Jvc29m
# dC5jb20vcGtpb3BzL0RvY3MvUmVwb3NpdG9yeS5odG0wCAYGZ4EMAQQCMA0GCSqG
# SIb3DQEBDAUAA4ICAQCAlM8r+t3hIb2h1lDTAx+iYkQlxFuU7QONeyIFIBZ29xvG
# l8pehKxErDzIniOpIX/eluUAwQKoaI0zwuKAdR0mrSHXCniMoLNko5W+5r7sXNam
# KX7QMV3BfGOX3gi9qVfxyUe7AHXbqQ8KBQHNYCnNFtQQHgARrlYhtyAKol5ctM0C
# Ac/y3oY7bTMsVJvnA5u7DVWPeXoST2KEMDeLBvJYq0IJZ6yMpDOWLZ4UP82bksyS
# hIB/XdawirIGLdseudryRxVMk313mAcjGRb59+Ittt6otVvYQWqH+PGrTUzEcez8
# aQuO3umoNZjKuFoX5VsPP/gSZse+orhG3zfZk9IDyE3DfUFrhvkv6H0tijK1D0uI
# GhwMBWSm9ktQ6oeU+aurZFx3MI+LODnHsbRFZAy11uMvwKq+ZNC1Se4tIM1u9piW
# AhnTPoh6mULKikHOVhHaO953tkzDCtjsse5GUKOx9yg9nqHKWMgnODp62/uPPzC/
# yDEISrXCcU7UB7tATr3zWNEdtM4d009iXWI6dV/SdcIIX44rpoLyCLw+nXjxp+fY
# /dygLO7UdSQaVaUFVj3K2nVyuujPspt5Lunc5FvuYPqmi/z8kASmmwbiF+W0P0UT
# WFaC84MWfU2h6MDg5s0oxmdNFK76jXr3wZfdSoV7FCKfq5GdeGoy5UwDQwMC0DGC
# A9QwggPQAgEBMHgwYTELMAkGA1UEBhMCVVMxHjAcBgNVBAoTFU1pY3Jvc29mdCBD
# b3Jwb3JhdGlvbjEyMDAGA1UEAxMpTWljcm9zb2Z0IFB1YmxpYyBSU0EgVGltZXN0
# YW1waW5nIENBIDIwMjACEzMAAABa9g1njIXt3QgAAAAAAFowDQYJYIZIAWUDBAIB
# BQCgggEtMBoGCSqGSIb3DQEJAzENBgsqhkiG9w0BCRABBDAvBgkqhkiG9w0BCQQx
# IgQg9QRgkMGfrYEABvWPVlOW9KoB5bZWxA/uftLPc2LC8qgwgd0GCyqGSIb3DQEJ
# EAIvMYHNMIHKMIHHMIGgBCBiuWRAi+p96PRsBt3TwW3jNozgPQS+Qco1CVm/NaU0
# QzB8MGWkYzBhMQswCQYDVQQGEwJVUzEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBv
# cmF0aW9uMTIwMAYDVQQDEylNaWNyb3NvZnQgUHVibGljIFJTQSBUaW1lc3RhbXBp
# bmcgQ0EgMjAyMAITMwAAAFr2DWeMhe3dCAAAAAAAWjAiBCDM3vdPvjov3ozbC7wJ
# yrFGg5LBFlgHj3OXna0FJywgpDANBgkqhkiG9w0BAQsFAASCAgC0PZIh0IIlT8Mx
# 5olW22FpYo/BPIBoa/OeYEB4UgMs8hPtZag0dcW4kAQT1i8SRdEuuSVzbq9SXGv1
# WVc0IQfgmurX2liWlD/mCY8Nq709tVW78+4eBB4FD8KmZlahniquK5n3huFLbEM8
# 1yFNy0YTArvP3RXcSzR3yDug4EYQJqZy+8+M+Gy/J5P3xdeUbl5StAgfJ4do1YiZ
# I13jpPvL0YDniQSGevyTjJbagWQ6LaE1NBtkQZqP1GSeLhSNYApLVTfRYBg7oYnY
# q7DNFEBi5EJgPAPADLhiS8m8ZAySNfVGa0knGfQqyzPVNJlQQpk+T5Ofl4FfbVIw
# p2ERR/y2gqj1kHWVRAenfL6u/EgNvBFYejVoh5tFZpsnPh30CxUAgolkIbKo55RO
# jK/EGimPwZ1px0KoNyvAYWA9S3dL3QvOaekfLzgXKHvNB1UWI4C40ctTDbqeKWe/
# KsM06LSKN4hSbD+jkjiiBkuY2ga1EVvf6F+iM0Gy9PQft6UcMmnBBn/Jf5qV8wRa
# F5FETITkLetGsuoKPclLgcN3Ib17QLd3rtsMxPtTjzRT+F6KCAhE6C9jy1c33X2y
# plFpPFi+6nItrXC6JceMPBRO52YBY/vbunxgdPfJlqXKjlBJNb6krzLbr9nyYnvn
# iYRBLzb1VcaPgpPOjAG+QrG+5CoEig==
# SIG # End signature block
